#!/bin/bash

# Exit immediately if a command exits with a non-zero status.
set -e

echo "Running tests..."
npm run test

echo "Tests passed! Proceeding with deployment..."

# Update the version, build the project, and publish
rm -rf ./dist/*
npm version patch --no-git-tag-version
npm run build
npm publish

echo "All operations completed successfully"


# git add .
# git commit -m ""
# git push -u origin main