// Generated by writeApiSchemas() from lambder/build. Do not edit.
//
// Every API's input schema, in the form a client posts, and output schema,
// in the form a client receives, as JSON Schema (draft 2020-12): what the
// mock validates its calls against, as the server does. Development only:
// it names every endpoint, so only the mock's setup imports it.

/** Every API the server registers: its input schema in its input form and its output schema in its output form, as JSON Schema. */
// prettier-ignore
export const apiSchemas = {
    "catalog.update": {
        "input": {
            "type": "object",
            "properties": {
                "product": {
                    "type": "object",
                    "properties": {
                        "sku": {
                            "type": "string"
                        },
                        "title": {
                            "type": "string",
                            "minLength": 1
                        }
                    },
                    "required": [
                        "sku",
                        "title"
                    ],
                    "additionalProperties": false
                },
                "attributes": {
                    "type": "object",
                    "propertyNames": {
                        "type": "string"
                    },
                    "additionalProperties": {
                        "type": "object",
                        "properties": {
                            "value": {
                                "type": "string"
                            },
                            "unit": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "value"
                        ],
                        "x-lambder-strip-unknown-keys": true
                    }
                },
                "dimensions": {
                    "type": "array",
                    "prefixItems": [
                        {
                            "type": "number",
                            "exclusiveMinimum": 0
                        },
                        {
                            "type": "number",
                            "exclusiveMinimum": 0
                        },
                        {
                            "type": "number",
                            "exclusiveMinimum": 0
                        }
                    ],
                    "items": false,
                    "minItems": 3,
                    "maxItems": 3
                },
                "tags": {
                    "type": "object",
                    "properties": {
                        "season": {
                            "type": "string",
                            "enum": [
                                "spring",
                                "summer",
                                "fall",
                                "winter"
                            ]
                        }
                    },
                    "required": [
                        "season"
                    ],
                    "additionalProperties": {}
                },
                "category": {
                    "$ref": "#/$defs/__schema0"
                },
                "price": {
                    "allOf": [
                        {
                            "type": "object",
                            "properties": {
                                "amount": {
                                    "type": "number",
                                    "minimum": 0
                                }
                            },
                            "required": [
                                "amount"
                            ],
                            "x-lambder-strip-unknown-keys": true
                        },
                        {
                            "type": "object",
                            "properties": {
                                "currency": {
                                    "type": "string",
                                    "enum": [
                                        "USD"
                                    ]
                                }
                            },
                            "required": [
                                "currency"
                            ],
                            "x-lambder-strip-unknown-keys": true
                        }
                    ]
                },
                "discontinuedAt": {
                    "anyOf": [
                        {
                            "type": "string",
                            "format": "date-time",
                            "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$"
                        },
                        {
                            "type": "null"
                        }
                    ]
                }
            },
            "required": [
                "product",
                "attributes",
                "dimensions",
                "tags",
                "category",
                "price",
                "discontinuedAt"
            ],
            "x-lambder-strip-unknown-keys": true,
            "$defs": {
                "__schema0": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string",
                            "minLength": 1
                        },
                        "children": {
                            "type": "array",
                            "items": {
                                "$ref": "#/$defs/__schema0"
                            }
                        }
                    },
                    "required": [
                        "name",
                        "children"
                    ],
                    "x-lambder-strip-unknown-keys": true
                }
            }
        },
        "output": {
            "type": "object",
            "properties": {
                "product": {
                    "type": "object",
                    "properties": {
                        "sku": {
                            "type": "string"
                        },
                        "title": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "sku",
                        "title"
                    ],
                    "x-lambder-strip-unknown-keys": true
                },
                "category": {
                    "$ref": "#/$defs/__schema0"
                },
                "tags": {
                    "type": "object",
                    "properties": {
                        "season": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "season"
                    ],
                    "additionalProperties": {}
                }
            },
            "required": [
                "product",
                "category",
                "tags"
            ],
            "x-lambder-strip-unknown-keys": true,
            "$defs": {
                "__schema0": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string",
                            "minLength": 1
                        },
                        "children": {
                            "type": "array",
                            "items": {
                                "$ref": "#/$defs/__schema0"
                            }
                        }
                    },
                    "required": [
                        "name",
                        "children"
                    ],
                    "x-lambder-strip-unknown-keys": true
                }
            }
        }
    },
    "orders.place": {
        "input": {
            "type": "object",
            "properties": {
                "customer": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string",
                            "minLength": 2,
                            "maxLength": 40
                        },
                        "email": {
                            "type": "string",
                            "format": "email",
                            "pattern": "^(?:[A-Za-z0-9_'+\\-]+\\.)*[A-Za-z0-9_'+\\-]*[A-Za-z0-9_+-]@(?:[A-Za-z0-9][A-Za-z0-9\\-]*\\.)+[A-Za-z]{2,}$"
                        }
                    },
                    "required": [
                        "name",
                        "email"
                    ],
                    "x-lambder-strip-unknown-keys": true
                },
                "items": {
                    "minItems": 1,
                    "maxItems": 5,
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "sku": {
                                "type": "string",
                                "pattern": "^[A-Z]{3}-\\d{3}$"
                            },
                            "quantity": {
                                "type": "integer",
                                "minimum": 1,
                                "maximum": 10
                            }
                        },
                        "required": [
                            "sku",
                            "quantity"
                        ],
                        "x-lambder-strip-unknown-keys": true
                    }
                },
                "delivery": {
                    "type": "string",
                    "enum": [
                        "pickup",
                        "courier"
                    ]
                },
                "note": {
                    "type": "string",
                    "maxLength": 200
                },
                "giftWrap": {
                    "default": false,
                    "type": "boolean"
                },
                "payment": {
                    "oneOf": [
                        {
                            "type": "object",
                            "properties": {
                                "method": {
                                    "type": "string",
                                    "const": "card"
                                },
                                "last4": {
                                    "type": "string",
                                    "minLength": 4,
                                    "maxLength": 4
                                }
                            },
                            "required": [
                                "method",
                                "last4"
                            ],
                            "x-lambder-strip-unknown-keys": true
                        },
                        {
                            "type": "object",
                            "properties": {
                                "method": {
                                    "type": "string",
                                    "const": "voucher"
                                },
                                "code": {
                                    "type": "string",
                                    "minLength": 6
                                }
                            },
                            "required": [
                                "method",
                                "code"
                            ],
                            "x-lambder-strip-unknown-keys": true
                        }
                    ]
                }
            },
            "required": [
                "customer",
                "items",
                "delivery",
                "payment"
            ],
            "x-lambder-strip-unknown-keys": true
        },
        "output": {
            "type": "object",
            "properties": {
                "orderNumber": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "placed",
                        "held"
                    ]
                },
                "total": {
                    "type": "number",
                    "minimum": 0
                },
                "lines": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "sku": {
                                "type": "string"
                            },
                            "quantity": {
                                "type": "integer",
                                "minimum": -9007199254740991,
                                "maximum": 9007199254740991
                            }
                        },
                        "required": [
                            "sku",
                            "quantity"
                        ],
                        "x-lambder-strip-unknown-keys": true
                    }
                },
                "courierNote": {
                    "default": "Leave it with the doorman",
                    "type": "string"
                }
            },
            "required": [
                "orderNumber",
                "status",
                "total",
                "lines",
                "courierNote"
            ],
            "x-lambder-strip-unknown-keys": true
        }
    },
    "stores.search": {
        "input": {
            "type": "object",
            "properties": {
                "query": {
                    "anyOf": [
                        {
                            "type": "string",
                            "minLength": 2
                        },
                        {
                            "type": "object",
                            "properties": {
                                "near": {
                                    "type": "object",
                                    "properties": {
                                        "lat": {
                                            "type": "number",
                                            "minimum": -90,
                                            "maximum": 90
                                        },
                                        "lng": {
                                            "type": "number",
                                            "minimum": -180,
                                            "maximum": 180
                                        }
                                    },
                                    "required": [
                                        "lat",
                                        "lng"
                                    ],
                                    "x-lambder-strip-unknown-keys": true
                                }
                            },
                            "required": [
                                "near"
                            ],
                            "x-lambder-strip-unknown-keys": true
                        }
                    ]
                },
                "limit": {
                    "default": 10,
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 50
                },
                "openNow": {
                    "type": "boolean"
                }
            },
            "required": [
                "query"
            ],
            "x-lambder-strip-unknown-keys": true
        },
        "output": {
            "type": "object",
            "properties": {
                "query": {
                    "anyOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "object",
                            "properties": {
                                "near": {
                                    "type": "object",
                                    "properties": {
                                        "lat": {
                                            "type": "number"
                                        },
                                        "lng": {
                                            "type": "number"
                                        }
                                    },
                                    "required": [
                                        "lat",
                                        "lng"
                                    ],
                                    "x-lambder-strip-unknown-keys": true
                                }
                            },
                            "required": [
                                "near"
                            ],
                            "x-lambder-strip-unknown-keys": true
                        }
                    ]
                },
                "limit": {
                    "type": "number"
                },
                "stores": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "borough": {
                                "type": "string",
                                "enum": [
                                    "Manhattan",
                                    "Brooklyn",
                                    "Queens",
                                    "Bronx",
                                    "Staten Island"
                                ]
                            }
                        },
                        "required": [
                            "name",
                            "borough"
                        ],
                        "x-lambder-strip-unknown-keys": true
                    }
                }
            },
            "required": [
                "query",
                "limit",
                "stores"
            ],
            "x-lambder-strip-unknown-keys": true
        }
    },
    "tickets.open": {
        "input": {
            "type": "object",
            "properties": {
                "subject": {
                    "type": "string",
                    "minLength": 3
                },
                "seat": {
                    "type": "string"
                },
                "guests": {
                    "default": 1,
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 4
                }
            },
            "required": [
                "subject",
                "seat"
            ],
            "x-lambder-strip-unknown-keys": true
        },
        "output": {
            "type": "object",
            "properties": {
                "ticketId": {
                    "type": "string"
                },
                "seat": {},
                "guests": {
                    "type": "number"
                }
            },
            "required": [
                "ticketId",
                "seat",
                "guests"
            ],
            "x-lambder-strip-unknown-keys": true
        }
    }
} as const;
