/**
 * lambder/build: writing and checking the signature file both sides ship.
 *
 * Files are written under the system's temporary directory, never into the
 * repository. The fresh-process verification runs real processes: a small
 * generator script and the module holding its instance, over the built
 * package (`dist`, which `npm test` builds ahead of the suite), since the
 * thing it exists to catch is a digest that differs between two processes.
 */

import { describe, it, expect, afterAll } from 'vitest';
import { spawnSync } from 'node:child_process';
import { lstatSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, statSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, relative } from 'node:path';
import { pathToFileURL } from 'node:url';
import { z } from 'zod';
import { initLambder } from '../src/core/Lambder.js';
import { writeApiSignatures } from '../src/build.js';
import { freshProcessNodeFlags } from '../src/build/writeApiSignatures.js';

const directory = mkdtempSync(join(tmpdir(), 'lambder-signatures-'));
afterAll(() => rmSync(directory, { recursive: true, force: true }));

let fileCount = 0;
const nextFile = () => join(directory, `apiSignatures-${fileCount++}.generated.ts`);

const appWith = (echoOutput: z.ZodType) => initLambder().create({ apiPath: '/api' })
    .addApi('echo', { input: z.object({ text: z.string() }), output: echoOutput }, async (_ctx, res) => res.api(null as never))
    .addApi('ping', { input: z.object({}), output: z.object({ ok: z.boolean() }) }, async (_ctx, res) => res.api({ ok: true }));

describe('writeApiSignatures', () => {
    it('writes a module exporting the same map the instance digests', async () => {
        const app = appWith(z.object({ text: z.string() }));
        const file = nextFile();

        const result = await writeApiSignatures(app, { file });

        expect(result).toMatchObject({ ok: true, written: true, count: 2, changed: [], added: ['echo', 'ping'], removedKeys: [] });
        const contents = readFileSync(file, 'utf8');
        expect(contents).toMatch(/^\/\/ Generated by writeApiSignatures\(\) from lambder\/build\. Do not edit\./);
        expect(contents).toContain('import type { LambderApiSignatureMap } from "lambder/client";');
        expect(contents).toContain('\n// prettier-ignore\nexport const apiSignatures');
        const map = JSON.parse(contents.slice(contents.indexOf('= ') + 2, contents.lastIndexOf(';')));
        expect(map).toEqual(await app.apiSignatures());
    });

    it('names the endpoints whose signatures moved, and says a removed one by its key', async () => {
        const file = nextFile();
        await writeApiSignatures(appWith(z.object({ text: z.string() })), { file });

        const reshaped = initLambder().create({ apiPath: '/api' })
            .addApi('echo', { input: z.object({ text: z.string() }), output: z.object({ text: z.string(), at: z.number() }) }, async (_ctx, res) => res.api(null as never))
            .addApi('added', { input: z.object({}), output: z.object({}) }, async (_ctx, res) => res.api({}));
        const result = await writeApiSignatures(reshaped, { file });

        expect(result.changed).toEqual(['echo']);
        expect(result.added).toEqual(['added']);
        expect(result.removedKeys).toHaveLength(1);
        expect(result.lines).toEqual([
            expect.stringContaining('✓ Wrote'),
            '  1 changed, 1 added, 1 removed (0 unchanged)',
            '  ~ echo',
            '  + added',
            expect.stringMatching(/^ {2}- [0-9a-f]+ \(removed: a key cannot be resolved back to its name\)$/),
        ]);
    });

    it('checks without writing: a file that matches passes, a stale one fails and names what moved', async () => {
        const file = nextFile();
        const app = appWith(z.object({ text: z.string() }));
        await writeApiSignatures(app, { file });
        const before = readFileSync(file, 'utf8');

        expect(await writeApiSignatures(app, { file, check: true })).toMatchObject({ ok: true, written: false });

        const stale = await writeApiSignatures(appWith(z.object({ text: z.string(), extra: z.string() })), { file, check: true });
        expect(stale).toMatchObject({ ok: false, written: false, changed: ['echo'] });
        expect(stale.lines[0]).toMatch(/is stale/);
        expect(readFileSync(file, 'utf8')).toBe(before);

        expect(await writeApiSignatures(app, { file: nextFile(), check: true })).toMatchObject({ ok: false, added: ['echo', 'ping'] });
    });

    it('compares the map the file holds, so line endings or a formatter leave it current', async () => {
        const file = nextFile();
        const app = appWith(z.object({ text: z.string() }));
        await writeApiSignatures(app, { file });
        writeFileSync(file, readFileSync(file, 'utf8').replace(/\n/g, '\r\n').replace(/ {4}/g, '  '));

        expect(await writeApiSignatures(app, { file, check: true })).toMatchObject({ ok: true, changed: [], added: [], removedKeys: [] });
    });

    it('leaves a file whose map is current alone, however it is formatted', async () => {
        // A CRLF checkout or a formatter's pass changes the text and not the
        // map: rewriting it would undo that pass on every run, and the pass
        // would redo it.
        const file = nextFile();
        const app = appWith(z.object({ text: z.string() }));
        await writeApiSignatures(app, { file });
        const reformatted = readFileSync(file, 'utf8').replace(/\n/g, '\r\n').replace(/ {4}/g, '  ').replace(/"/g, "'");
        writeFileSync(file, reformatted);

        expect(await writeApiSignatures(app, { file })).toMatchObject({ ok: true, written: false });
        expect(readFileSync(file, 'utf8')).toBe(reformatted);
    });

    it('replaces the file with a finished one renamed over it, and leaves nothing beside it', async () => {
        const file = nextFile();
        await writeApiSignatures(appWith(z.object({ text: z.string() })), { file });
        const before = statSync(file).ino;

        expect(await writeApiSignatures(appWith(z.object({ text: z.string(), extra: z.string() })), { file })).toMatchObject({ written: true, changed: ['echo'] });

        // Another inode: the file was swapped whole, never rewritten in place
        // where a build reading it could catch half of it.
        expect(statSync(file).ino).not.toBe(before);
        expect(readdirSync(directory).filter((name) => name.endsWith('.tmp'))).toEqual([]);
    });

    it('reads a map whose keys a formatter unquoted, in check and in write mode alike', async () => {
        // Prettier's default quoteProps ("as-needed"), Biome's and ESLint's
        // quote-props take the quotes off every key that is a valid
        // identifier, which a hex key starting with a letter is, and keep them
        // on a key starting with a digit. The prettier-ignore line spares the
        // map from Prettier, but not from the other two.
        const file = nextFile();
        const app = appWith(z.object({ text: z.string() }));
        await writeApiSignatures(app, { file });
        const unquoted = readFileSync(file, 'utf8')
            .replace(/"([0-9a-f]+)": "([0-9a-f]+)"/g, (_pair, key: string, signature: string) => `${/^[a-f]/.test(key) ? key : `'${key}'`}: '${signature}'`)
            .replace(/ {4}/g, '  ')
            .replace(/'\n}/, "',\n}");
        // One key of each kind, or the rewrite proves nothing.
        expect(unquoted).toMatch(/\n {2}[a-f][0-9a-f]{15}: '/);
        expect(unquoted).toMatch(/\n {2}'[0-9][0-9a-f]{15}': '/);
        writeFileSync(file, unquoted);

        expect(await writeApiSignatures(app, { file, check: true })).toMatchObject({ ok: true, changed: [], added: [], removedKeys: [] });
        expect(await writeApiSignatures(app, { file })).toMatchObject({ ok: true, written: false, changed: [], added: [], removedKeys: [] });
        expect(readFileSync(file, 'utf8')).toBe(unquoted);
        expect(await writeApiSignatures(appWith(z.object({ text: z.string(), extra: z.string() })), { file, check: true })).toMatchObject({ ok: false, changed: ['echo'], added: [], removedKeys: [] });
    });

    it('writes through a symlink into the file it names, and leaves the link a link', async () => {
        const realDirectory = join(directory, `real-${fileCount}`);
        mkdirSync(realDirectory);
        const realFile = join(realDirectory, 'apiSignatures.generated.ts');
        const link = nextFile();
        await writeApiSignatures(appWith(z.object({ text: z.string() })), { file: realFile });
        symlinkSync(realFile, link);

        const reshaped = appWith(z.object({ text: z.string(), extra: z.string() }));
        expect(await writeApiSignatures(reshaped, { file: link })).toMatchObject({ ok: true, written: true, changed: ['echo'] });

        expect(lstatSync(link).isSymbolicLink()).toBe(true);
        expect(await writeApiSignatures(reshaped, { file: realFile, check: true })).toMatchObject({ ok: true });
        expect(readdirSync(realDirectory)).toEqual(['apiSignatures.generated.ts']);
    });

    it('leaves a file that already holds the signatures untouched', async () => {
        const file = nextFile();
        const app = appWith(z.object({ text: z.string() }));
        expect(await writeApiSignatures(app, { file })).toMatchObject({ ok: true, written: true });
        const again = await writeApiSignatures(app, { file });
        expect(again).toMatchObject({ ok: true, written: false });
        expect(again.lines[0]).toMatch(/is up to date/);
    });

    it('writes the style an app asks for, and reads either style back', async () => {
        const file = nextFile();
        const app = appWith(z.object({ text: z.string() }));
        const style = { quotes: 'single', semicolons: false, header: 'Generated by ./compile api-signatures. Do not edit.\n\nBoth sides ship this file.' } as const;

        await writeApiSignatures(app, { file, ...style });

        const contents = readFileSync(file, 'utf8');
        expect(contents.startsWith('// Generated by ./compile api-signatures. Do not edit.\n//\n// Both sides ship this file.\nimport type')).toBe(true);
        expect(contents).toContain("import type { LambderApiSignatureMap } from 'lambder/client'\n");
        expect(contents).not.toContain('"');
        expect(contents.trimEnd().endsWith('}')).toBe(true);
        expect(await writeApiSignatures(app, { file, check: true, ...style })).toMatchObject({ ok: true, changed: [], added: [] });
    });
});

describe('writeApiSignatures in a fresh process', () => {
    const buildEntry = pathToFileURL(new URL('../dist/build.js', import.meta.url).pathname).href;
    /** A stand-in for a loader such as tsx: the instance module refuses to load without it, so a fresh process has to inherit it. */
    const loaderFlag = ['--import', 'data:text/javascript,globalThis.lambderTestLoaderRan=true'];

    /**
     * A generator script over the built package and the module holding its
     * instance, as an app keeps them: the script imports the instance and
     * names its module for the fresh process. Each appends a line to a log
     * when it runs, so a test can count the runs. The instance digests the
     * same in every process, or differently.
     */
    const runGenerator = (options: {
        stable: boolean;
        moduleAs?: 'path' | 'url' | 'urlString';
        exportName?: string;
        removeModuleBeforeCall?: boolean;
        /** Check a file this same process wrote a moment before, rather than write it. */
        check?: boolean;
        /** Run the script as `node --input-type=module -e <source>` rather than as a file. */
        runAsEval?: boolean;
    }) => {
        const run = fileCount++;
        const file = join(directory, `apiSignatures-${run}.generated.ts`);
        const log = join(directory, `runs-${run}.log`);
        const instanceModule = join(directory, `instance-${run}.mjs`);
        writeFileSync(instanceModule, [
            'import { appendFileSync } from "node:fs";',
            'if(!globalThis.lambderTestLoaderRan) throw new Error("loaded without the generator\'s --import flag");',
            `appendFileSync(${JSON.stringify(log)}, "module\\n");`,
            'console.log("the module\'s own output, which the verdict line has to survive");',
            `const signature = ${options.stable ? '"0b0b"' : 'process.pid.toString(16)'};`,
            'export default { apiSignatureEntries: async () => [{ name: "report.daily", key: "0a0a", signature }] };',
        ].join('\n'));
        // The generator runs in this process's working directory.
        const moduleOption = options.moduleAs === 'path' ? JSON.stringify(relative(process.cwd(), instanceModule))
            : options.moduleAs === 'urlString' ? JSON.stringify(pathToFileURL(instanceModule).href)
            : `new URL(${JSON.stringify(pathToFileURL(instanceModule).href)})`;
        const script = join(directory, `generate-${run}.mjs`);
        writeFileSync(script, [
            'import { appendFileSync, rmSync } from "node:fs";',
            `import { writeApiSignatures } from ${JSON.stringify(buildEntry)};`,
            `import instance from ${JSON.stringify(pathToFileURL(instanceModule).href)};`,
            `appendFileSync(${JSON.stringify(log)}, "generator\\n");`,
            ...(options.removeModuleBeforeCall ? [`rmSync(${JSON.stringify(instanceModule)});`] : []),
            `const verifyInFreshProcess = { module: ${moduleOption}${options.exportName ? `, exportName: ${JSON.stringify(options.exportName)}` : ''} };`,
            ...(options.check ? [`await writeApiSignatures(instance, { file: ${JSON.stringify(file)} });`] : []),
            `const result = await writeApiSignatures(instance, { file: ${JSON.stringify(file)}, verifyInFreshProcess${options.check ? ', check: true' : ''} });`,
            'process.stdout.write(JSON.stringify(result));',
            'process.exit(result.ok ? 0 : 1);',
        ].join('\n'));
        const child = spawnSync(process.execPath, [...loaderFlag, ...(options.runAsEval ? ['--input-type=module', '-e', readFileSync(script, 'utf8')] : [script])], { encoding: 'utf8' });
        return {
            status: child.status,
            result: JSON.parse(child.stdout.slice(child.stdout.indexOf('{'))),
            runs: readFileSync(log, 'utf8').trim().split('\n'),
        };
    };

    it('passes when a second process digests the same signatures, loading the instance module and never the script', () => {
        const { status, result, runs } = runGenerator({ stable: true });
        expect(status).toBe(0);
        expect(result.lines.at(-1)).toBe('✓ a fresh process digests the same signatures');
        // The generator ran once; the module once for it and once in the
        // fresh process, which got the generator's --import flag too.
        expect(runs).toEqual(['module', 'generator', 'module']);
    });

    it('takes the module as a path relative to the working directory as well as a URL', () => {
        const { status, result } = runGenerator({ stable: true, moduleAs: 'path' });
        expect(status).toBe(0);
        expect(result.lines.at(-1)).toBe('✓ a fresh process digests the same signatures');
    });

    it('takes a file URL given as a string, as import.meta.resolve() answers it', () => {
        const { status, result } = runGenerator({ stable: true, moduleAs: 'urlString' });
        expect(result.lines.at(-1)).toBe('✓ a fresh process digests the same signatures');
        expect(status).toBe(0);
    });

    it('verifies in check mode too, against the file on disk', () => {
        const { status, result, runs } = runGenerator({ stable: true, check: true });
        expect(status).toBe(0);
        expect(result).toMatchObject({ ok: true, written: false });
        expect(result.lines).toEqual([expect.stringMatching(/matches the 1 registered APIs$/), '✓ a fresh process digests the same signatures']);
        expect(runs).toEqual(['module', 'generator', 'module']);
    });

    it('fails a check whose file a second process digests differently', () => {
        const { status, result } = runGenerator({ stable: false, check: true });
        expect(status).toBe(1);
        expect(result).toMatchObject({ ok: false, written: false });
        expect(result.lines).toContainEqual(expect.stringMatching(/a fresh process digests different signatures/));
    });

    it('verifies from a generator run as node --input-type=module -e', () => {
        const { status, result } = runGenerator({ stable: true, runAsEval: true });
        expect(result.lines.at(-1)).toBe('✓ a fresh process digests the same signatures');
        expect(status).toBe(0);
    });

    it('fails, naming the endpoint, when a second process digests differently', () => {
        const { status, result } = runGenerator({ stable: false });
        expect(status).toBe(1);
        expect(result.ok).toBe(false);
        expect(result.written).toBe(true);
        expect(result.lines).toContainEqual(expect.stringMatching(/a fresh process digests different signatures/));
        expect(result.lines).toContain('    ~ report.daily');
    });

    it('fails, saying so, when the export named is not an instance', () => {
        const { status, result } = runGenerator({ stable: true, exportName: 'lambder' });
        expect(status).toBe(1);
        expect(result.lines).toContainEqual(expect.stringMatching(/never compared it: .* has no export "lambder" that lists API signatures/));
    });

    it('fails, with the error, when the module does not load in the fresh process', () => {
        const { status, result } = runGenerator({ stable: true, removeModuleBeforeCall: true });
        expect(status).toBe(1);
        expect(result.lines).toContainEqual(expect.stringMatching(/never compared it: loading .*instance-\d+\.mjs failed \(exit status 1\)/));
        expect(result.lines.join('\n')).toMatch(/ERR_MODULE_NOT_FOUND|Cannot find module/);
    });
});

describe('The Node flags a fresh process inherits', () => {
    it('keeps the loaders, and drops the inspector, watch mode, the test runner and -e/-p with their values', () => {
        // A child started with the parent's --inspect-brk or --watch would
        // wait for a debugger or a file change until the timeout.
        expect(freshProcessNodeFlags([
            '--import', 'tsx', '--inspect-brk', '--inspect-port', '9230', '--inspect=127.0.0.1:0', '--require=./setup.cjs',
            '--watch', '--watch-path', 'src', '--watch-preserve-output', '--conditions', 'development', '--debug-port=9231',
            '--test', '--test-reporter=tap', '--test-name-pattern', 'nightly', '-e', 'run()', '--print=1',
            '--loader', 'ts-node/esm', '--no-warnings',
        ])).toEqual(['--import', 'tsx', '--require=./setup.cjs', '--conditions', 'development', '--loader', 'ts-node/esm', '--no-warnings']);
    });

    it('drops --input-type in both spellings and an eval cluster such as -pe, each with its value', () => {
        // Beside an entry file, Node refuses --input-type outright
        // (ERR_INPUT_TYPE_NOT_ALLOWED), and -pe runs its code in place of the
        // entry as -e does; Node keeps the cluster as one element.
        expect(freshProcessNodeFlags([
            '--input-type=module', '--import', 'tsx', '--input-type', 'commonjs', '-pe', 'process.version', '-C', 'development', '--print', '1', '-r', './setup.cjs',
        ])).toEqual(['--import', 'tsx', '-C', 'development', '-r', './setup.cjs']);
    });
});
